// ProEssentialsJS -- Copyright 1994-2026 Gigasoft, Inc. All rights reserved.
// Commercial product, free for commercial use under USD 250,000 annual
// revenue. See PEJS-LICENSE.md -- https://www.gigasoft.com
//
// GENERATED BY tools\gen-web-events.py -- DO NOT EDIT.
// Merges the .NET event handles into PeControl. See
// Wasm\PLAN-EVENTS-DOTNET-20260818.md.

/** One .NET event. `add`/`remove` are C#'s `+=` and `-=`. */
interface PeEventHandle {
  /** Subscribe. Returns the control, so calls chain. */
  add(fn: (sender: PeControl, ev: Record<string, unknown>) => unknown): PeControl;
  /** Unsubscribe one handler. */
  remove(fn: (sender: PeControl, ev: Record<string, unknown>) => unknown): PeControl;
  /** Drop every handler. */
  clear(): PeControl;
  readonly count: number;
}

/** Every .NET event name. A given control carries a SUBSET. */
type PeEventName =
  | 'PeCursorMoved'
  | 'PeCustomGridNumber'
  | 'PeCustomMenu'
  | 'PeCustomTrackingDataText'
  | 'PeCustomTrackingOtherText'
  | 'PeCustomizeDlg'
  | 'PeDataHotSpot'
  | 'PeGraphAnnotHotSpot'
  | 'PeGraphAnnotationMoved'
  | 'PeGraphHotSpot'
  | 'PeGridNumber'
  | 'PeHorzLineAnnotHotSpot'
  | 'PeHorzScroll'
  | 'PeMainTitle'
  | 'PeMultiBottomTitle'
  | 'PeMultiSubTitle'
  | 'PeParamUpdate'
  | 'PePointHotSpot'
  | 'PePopupMenu'
  | 'PePreCursorMove'
  | 'PePreHScroll'
  | 'PePreVScroll'
  | 'PeSubTitle'
  | 'PeSubsetHotSpot'
  | 'PeTAMoved'
  | 'PeTableAnnotation'
  | 'PeTableHotSpot'
  | 'PeVertLineAnnotHotSpot'
  | 'PeVertScroll'
  | 'PeXAxis'
  | 'PeXAxisAnnotHotSpot'
  | 'PeXAxisLabel'
  | 'PeXAxisLineAnnotHotSpot'
  | 'PeYAxis'
  | 'PeYAxisAnnotHotSpot'
  | 'PeYAxisLabel'
  | 'PeYAxisLineAnnotHotSpot'
  | 'PeZAxisLineAnnotHotSpot'
  | 'PeZoomIn'
  | 'PeZoomOut'
  ;

declare interface PeControl {
  /** Names this control declares in .NET that cannot fire on
   *  the web build. Those handles are ABSENT, not dead. */
  readonly eventsBlocked?: readonly string[];
  /** Also reachable as `onCursorMoved`. BOTH fire, camelCase first. */
  readonly PeCursorMoved?: PeEventHandle;
  /** Also reachable as `onCustomGridNumber`. BOTH fire, camelCase first. */
  readonly PeCustomGridNumber?: PeEventHandle;
  readonly PeCustomMenu?: PeEventHandle;
  /** Also reachable as `onCustomTrackingDataText`. BOTH fire, camelCase first. */
  readonly PeCustomTrackingDataText?: PeEventHandle;
  /** Also reachable as `onCustomTrackingOtherText`. BOTH fire, camelCase first. */
  readonly PeCustomTrackingOtherText?: PeEventHandle;
  /** NOT AVAILABLE here: both 2D send sites are SHUT (RBASEENT.CPP:11466) and the customize dialog is a WinUI/WinForms construct */
  readonly PeCustomizeDlg?: PeEventHandle;
  readonly PeDataHotSpot?: PeEventHandle;
  readonly PeGraphAnnotHotSpot?: PeEventHandle;
  /** Also reachable as `onGraphAnnotationMoved`. BOTH fire, camelCase first. */
  readonly PeGraphAnnotationMoved?: PeEventHandle;
  readonly PeGraphHotSpot?: PeEventHandle;
  readonly PeGridNumber?: PeEventHandle;
  readonly PeHorzLineAnnotHotSpot?: PeEventHandle;
  /** Also reachable as `onHorzScroll`. BOTH fire, camelCase first. */
  readonly PeHorzScroll?: PeEventHandle;
  readonly PeMainTitle?: PeEventHandle;
  readonly PeMultiBottomTitle?: PeEventHandle;
  readonly PeMultiSubTitle?: PeEventHandle;
  /** Also reachable as `onParamUpdate`. BOTH fire, camelCase first. */
  readonly PeParamUpdate?: PeEventHandle;
  readonly PePointHotSpot?: PeEventHandle;
  /** Also reachable as `onPopupMenu`. BOTH fire, camelCase first. */
  readonly PePopupMenu?: PeEventHandle;
  /** Also reachable as `onPreCursorMove`. BOTH fire, camelCase first. */
  readonly PePreCursorMove?: PeEventHandle;
  readonly PePreHScroll?: PeEventHandle;
  readonly PePreVScroll?: PeEventHandle;
  readonly PeSubTitle?: PeEventHandle;
  readonly PeSubsetHotSpot?: PeEventHandle;
  /** Also reachable as `onTAMoved`. BOTH fire, camelCase first. */
  readonly PeTAMoved?: PeEventHandle;
  readonly PeTableAnnotation?: PeEventHandle;
  readonly PeTableHotSpot?: PeEventHandle;
  readonly PeVertLineAnnotHotSpot?: PeEventHandle;
  /** Also reachable as `onVertScroll`. BOTH fire, camelCase first. */
  readonly PeVertScroll?: PeEventHandle;
  readonly PeXAxis?: PeEventHandle;
  readonly PeXAxisAnnotHotSpot?: PeEventHandle;
  readonly PeXAxisLabel?: PeEventHandle;
  readonly PeXAxisLineAnnotHotSpot?: PeEventHandle;
  readonly PeYAxis?: PeEventHandle;
  readonly PeYAxisAnnotHotSpot?: PeEventHandle;
  readonly PeYAxisLabel?: PeEventHandle;
  readonly PeYAxisLineAnnotHotSpot?: PeEventHandle;
  readonly PeZAxisLineAnnotHotSpot?: PeEventHandle;
  /** Also reachable as `onZoomIn`. BOTH fire, camelCase first. */
  readonly PeZoomIn?: PeEventHandle;
  /** Also reachable as `onZoomOut`. BOTH fire, camelCase first. */
  readonly PeZoomOut?: PeEventHandle;
}
